### ISSUE TITLE
lzo-java uses GPL-3 license 

### ISSUE THREAD

**Issue by ksawerykarwacki** [adform/stream-loader#41]
Currently stream-loader uses `org.anarres.lzo:lzo-commons` which is based on GPL-3 license (https://github.com/shevek/lzo-java/issues/9). This means that stream-loader and any software using it should be released under GPL-3. 

Can you change your license to reflect that and avoid misinformation?

**Comment by sauliusvl** [comment]
good catch, I think I originally added all compressions "just-in-case", probably would be easier to just remove it than to change license. @HubertTatar wdyt?

**Comment by ksawerykarwacki** [comment]
Thanks for quick fix. Any chance for release containing this?

**Comment by HubertTatar** [comment]
@ksawerykarwacki v0.2.14 released
